// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKY8fMRS1tg7Dy-wCYjl7A5-iUDtJa2Y',
    appId: '1:611705476773:web:18614d5f4a4623341f9f4c',
    messagingSenderId: '611705476773',
    projectId: 'chat-tharwat-564da',
    authDomain: 'chat-tharwat-564da.firebaseapp.com',
    storageBucket: 'chat-tharwat-564da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD36srYwxMDatjCGYDGzmfn4U57pO9OTyQ',
    appId: '1:611705476773:android:06fe10ffe4468f951f9f4c',
    messagingSenderId: '611705476773',
    projectId: 'chat-tharwat-564da',
    storageBucket: 'chat-tharwat-564da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBScSXRSM5g-fllFVILymvbKZw4xJXbfAk',
    appId: '1:611705476773:ios:f374315c323696cf1f9f4c',
    messagingSenderId: '611705476773',
    projectId: 'chat-tharwat-564da',
    storageBucket: 'chat-tharwat-564da.appspot.com',
    iosClientId: '611705476773-3ck1m92s2b2tlbomk1fsv7j9m8ulrek1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBScSXRSM5g-fllFVILymvbKZw4xJXbfAk',
    appId: '1:611705476773:ios:f374315c323696cf1f9f4c',
    messagingSenderId: '611705476773',
    projectId: 'chat-tharwat-564da',
    storageBucket: 'chat-tharwat-564da.appspot.com',
    iosClientId: '611705476773-3ck1m92s2b2tlbomk1fsv7j9m8ulrek1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
